namespace DrawEverything.BarAndQrCode.QRCoder
{
    internal abstract class AbstractQrCode
    {
        protected QrCodeData QrCodeData { get; set; }

        protected AbstractQrCode() {
        }

        protected AbstractQrCode(QrCodeData data) {
            this.QrCodeData = data;
        }

        /// <summary>
        /// Set a QRCodeData object that will be used to generate QR code. Used in COM Objects connections
        /// </summary>
        /// <param name="data">Need a QRCodeData object generated by QRCodeGenerator.CreateQrCode()</param>
        public virtual void SetQrCodeData(QrCodeData data) {
            this.QrCodeData = data;
        }

        public void Dispose()
        {
            this.QrCodeData = null;
        }
    }
}